export const PILLAR_SLUGS = [
  'pain-management',
  'orthopedics',
  'physical-therapy',
  'immediate-care',
  'internal-medicine',
  'injury-services',
  'diagnostic-surgical-services',
] as const;

export const DETAIL_MAP: Record<string, string[]> = {
  'pain-management': [
    'epidural-steroid-injections',
    'facet-joint-blocks',
    'nerve-blocks',
    'trigger-point-injections',
    'radiofrequency-ablation',
    'joint-injections',
    'bursa-injections',
    'sacroiliac-joint-injections',
    'spinal-cord-stimulation',
    'transforaminal-epidural-injections',
    'selective-nerve-root-blocks',
    'intercostal-nerve-blocks',
    'stellate-ganglion-block',
  ],
  'orthopedics': [
    'joint-replacement',
    'spine-surgery',
    'fracture-care',
    'sports-medicine',
    'arthroscopic-surgery',
    'fracture-clinic',
  ],
  'physical-therapy': [
    'orthopedic-rehab',
    'work-injury-rehab',
    'auto-injury-rehab',
    'post-surgical-rehab',
    'sports-rehab',
    'balance-and-strength-programs',
  ],
  'immediate-care': [
    'walk-in-clinic',
    'minor-injuries',
    'minor-illnesses',
    'work-injury-urgent-care',
    'on-site-medications',
  ],
  'internal-medicine': [
    'primary-care',
    'chronic-disease-management',
    'annual-physicals',
    'preventive-care',
    'preoperative-clearance',
  ],
  'injury-services': [
    'motor-vehicle-accidents',
    'personal-injury',
    'workers-compensation',
    'workplace-injuries',
  ],
  'diagnostic-surgical-services': [
    'diagnostic-imaging',
    'x-rays',
    'mri-referrals',
    'in-house-lab',
    'blood-work',
    'outpatient-surgery-center',
    'same-day-procedures',
    'pain-management-procedures',
    'orthopedic-procedures',
    'neurological-procedures',
    'general-surgery',
  ],
};
