// src/content/services/pain-management/radiofrequency-ablation.ts
// Rand Medical Center — Radiofrequency Ablation (Service Detail)

import type { SEOMeta, HeroSection, KeyFact, ConditionLink, TreatmentLink, FeatureItem, FAQItem } from "@/types/content";

export const seo: SEOMeta = {
  title: "Radiofrequency Ablation in Arlington Heights, IL | Rand Medical Center",
  description: "Radiofrequency ablation (RFA) in Arlington Heights, IL for longer-lasting back and neck pain relief by gently heating selected pain-signaling nerves. Call (224) 735-3522.",
  keywords: ["radiofrequency ablation Arlington Heights", "radiofrequency ablation near me", "radiofrequency ablation treatment"],
  canonical: "https://www.randmedicalcenter.com/services/pain-management/radiofrequency-ablation",
};

export const hero: HeroSection = {
  eyebrow: "Pain Management",
  headline: "Radiofrequency Ablation in Arlington Heights, IL",
  subheadline: "Radiofrequency ablation (RFA) in Arlington Heights, IL for longer-lasting back and neck pain relief by gently heating selected pain-signaling nerves.",
  primaryCTA: { text: "Schedule a Consultation", href: "https://www.tebra.com/care/practice/rand-medical-center-456192", variant: "primary" },
  secondaryCTA: { text: "Call (224) 735-3522", href: "tel:+12247353522", variant: "secondary" },
};

export const overview = {
  headline: "What Are Radiofrequency Ablation?",
  body: "Radiofrequency ablation (RFA) is a minimally invasive procedure that uses heat generated by radio waves to disrupt specific nerves that carry pain signals. By creating a small, controlled lesion on the target nerve, RFA can reduce or eliminate pain for months to over a year in many patients.\n\nRFA is most commonly used for facet joint pain in the neck or back — the same joints targeted by facet joint blocks. In fact, if diagnostic facet joint blocks confirm that your pain comes from a specific facet joint, RFA is often the next step for longer-lasting relief.\n\nThe procedure is performed on an outpatient basis under fluoroscopic guidance at Rand Medical Center.",
  keyFacts: [
    { label: "Procedure Time", value: "15–30 minutes" },
    { label: "Recovery", value: "Resume normal activities in 1–2 days" },
    { label: "Guidance", value: "Fluoroscopy or ultrasound" },
  ] as KeyFact[],
};

export const howItWorks = {
  headline: "How Radiofrequency Ablation Work",
  body: "After numbing the skin, your physician uses fluoroscopy to guide a special needle with a heated tip to the target nerve. A test stimulation confirms correct placement, then controlled heat is applied to create a small lesion that interrupts pain signal transmission. The procedure takes about 30–60 minutes.",
};

export const conditionsTreated = {
  headline: "Conditions Treated",
  conditions: [
    {
        "name": "Facet Joint Syndrome",
        "slug": "facet-joint-syndrome",
        "href": "/conditions/spine/facet-syndrome"
    },
    {
        "name": "Chronic Pain",
        "slug": "chronic-pain",
        "href": "/conditions/pain-syndromes/chronic-pain"
    },
    {
        "name": "Back Pain",
        "slug": "back-pain",
        "href": "/conditions/spine/back-pain"
    },
    {
        "name": "Neck Pain",
        "slug": "neck-pain",
        "href": "/conditions/spine/neck-pain"
    }
] as ConditionLink[],
};

export const benefits = {
  headline: "Benefits of Radiofrequency Ablation",
  items: [
    "Targeted delivery of medication directly to the pain source",
    "Minimally invasive with no incisions",
    "Performed on an outpatient basis — go home the same day",
    "Can reduce or eliminate the need for stronger pain medications",
    "Helps diagnose the exact source of your pain",
    "May improve your ability to participate in physical therapy",
  ],
};

export const whatToExpect = {
  headline: "What to Expect",
  body: "The procedure is performed in our clinic or outpatient surgery center. Plan for about 60–90 minutes total including check-in and recovery. You'll need someone to drive you home. Most patients return to normal activities within 1–2 days. Your doctor will schedule a follow-up to assess your response.",
};

export const risks = {
  headline: "Risks and Considerations",
  body: "This procedure is generally considered safe when performed by an experienced physician using image guidance. As with any medical procedure, there are potential risks, including temporary soreness at the injection site, mild headache, temporary increase in pain, and rare complications such as infection or nerve injury. Your doctor will discuss the specific risks and benefits with you before the procedure.",
};

export const whyChooseUs = {
  headline: "Why Choose Rand Medical Center?",
  features: [
    { icon: "target", title: "Image-Guided Precision", description: "Every procedure is performed under fluoroscopic or ultrasound guidance for accurate needle placement." },
    { icon: "award", title: "Experienced Specialists", description: "Our pain management physicians perform hundreds of procedures each year." },
    { icon: "refresh-cw", title: "Coordinated Follow-Up", description: "Physical therapy and additional treatments are available right here for seamless recovery." },
  ] as FeatureItem[],
};

export const relatedTreatments = {
  headline: "Related Treatments",
  items: [
    {
        "name": "Facet Joint Blocks",
        "slug": "facet-joint-blocks",
        "href": "/services/pain-management/facet-joint-blocks"
    },
    {
        "name": "Epidural Steroid Injections",
        "slug": "epidural-steroid-injections",
        "href": "/services/pain-management/epidural-steroid-injections"
    },
    {
        "name": "Spinal Cord Stimulation",
        "slug": "spinal-cord-stimulation",
        "href": "/services/pain-management/spinal-cord-stimulation"
    }
] as TreatmentLink[],
};

export const ctaSection = {
  headline: "Find Out If Radiofrequency Ablation Are Right for You",
  body: "Schedule a consultation with our pain management team in Arlington Heights, IL to discuss whether radiofrequency ablation could help with your condition.",
  primaryCTA: { text: "Schedule a Consultation", href: "https://www.tebra.com/care/practice/rand-medical-center-456192", variant: "primary" as const },
  secondaryCTA: { text: "Call (224) 735-3522", href: "tel:+12247353522", variant: "secondary" as const },
};

export const faqs: FAQItem[] = [
  { question: "How quickly will I feel results?", answer: "Many patients notice some relief from the local anesthetic within hours. The full anti-inflammatory effect of the steroid typically develops over 2–7 days." },
  { question: "Is the procedure painful?", answer: "Most patients describe mild pressure or discomfort during the injection. The area is numbed with local anesthetic beforehand, and sedation options are available if needed." },
  { question: "Does insurance cover this procedure?", answer: "Most health insurance plans and workers' compensation programs cover radiofrequency ablation when medically necessary. Our billing team can verify your coverage before the procedure." },
  { question: "How many treatments will I need?", answer: "It depends on your condition and response. Some patients get significant relief from a single injection, while others benefit from a series of 2–3 over several weeks. Your doctor will recommend a plan based on your specific situation." },
];
